
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=DriveDb;Username=postgres;Password=sua_senha_aqui
    depends_on:
      - postgres_db

  # Serviço do PostgreSQL
  postgres_db:
    image: postgres:17-alpine
    container_name: Drive_db
    environment:
      POSTGRES_DB: DriveDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha_aqui
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: